name: poke_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_meedu: ^9.2.1
  json_annotation: ^4.12.0
  go_router: ^17.2.3
  shimmer: ^3.0.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.13.2
  lottie: ^3.3.3
  extended_image: ^10.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/pokeball.png
    - assets/lotties/pokeball_loading.json
